# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20200624_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_id',
        ),
        migrations.AddField(
            model_name='goal',
            name='id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
