# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_exercise_part_of'),
        ('fitness', '0004_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(to='main.Exercise'),
        ),
    ]
