# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_routine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='name',
            field=models.CharField(auto_created=True, max_length=30, null=True),
        ),
    ]
