# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_auto_20200626_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(related_name='routines', to='main.Exercise'),
        ),
    ]
