# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-23 19:34
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment_needed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BARBELL', 'Barbell'), ('DUMBBELL', 'Dumbbell'), ('KETTLEBELL', 'Kettlebell'), ('PULLUPBAR', 'Pullup Bar'), ('FOAMROLLER', 'Foam roller')], max_length=48),
        ),
    ]
