# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_routine'),
        ('main', '0003_auto_20200624_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='part_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.Routine'),
        ),
    ]
