# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_exercise_part_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.Routine'),
        ),
    ]
