# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200626_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='part_of',
        ),
    ]
